### ISSUE TITLE
这是测通了吗?

### ISSUE THREAD

**Issue by tellmewhattodo** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#1]
大哥给个信,想入手p52了

**Comment by liuyishengalan** [comment]
嘻嘻，对的，可以使用

**Comment by liuyishengalan** [comment]
![img_20190214_015136](https://user-images.githubusercontent.com/41530282/52907178-b71b1780-3296-11e9-81e7-88538fdf6edf.jpg)

**Comment by liuyishengalan** [comment]
![img_20190215_214336](https://user-images.githubusercontent.com/41530282/52907184-eb8ed380-3296-11e9-8088-557281bb99f0.jpg)

**Comment by fangjj** [comment]
@liuyishengalan 有视频教程吗，新手不会弄。或者有参考资料吗。谢谢。

**Comment by fangjj** [comment]
@liuyishengalan 能写一下你的p52配置吗，方便对照。

**Comment by liuyishengalan** [comment]
i7 8750h
quadro p1000
32G ddr4 2666 hyper x
4k display
disk: WD black SN700 & Samsung 970evo

**Comment by fangjj** [comment]
请教一下，黑苹果后的p52还能支持最大128g内存吗


 
---原始邮件---
发件人: "YishengLiu"<notifications@github.com>
发送时间: 2019年4月30日(星期二) 下午5:07
收件人: "liuyishengalan/ThinkPad-P52-Hackintosh-10.14.X-"<ThinkPad-P52-Hackintosh-10.14.X-@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"redim"<fangjimjim@qq.com>;
主题: Re: [liuyishengalan/ThinkPad-P52-Hackintosh-10.14.X-] 这是测通了吗? (#1)



i7 8750h
 quadro p1000
 32G ddr4 2666 hyper x
 4k display
 disk: WD black SN700 & Samsung 970evo

**Comment by liuyishengalan** [comment]
of course, P52 always supports 128G ddr4. It can not be modified.


发送自我的Sony Xperia智能手机


---- redim编写 ----

请教一下，黑苹果后的p52还能支持最大128g内存吗



---原始邮件---
发件人: "YishengLiu"<notifications@github.com>
发送时间: 2019年4月30日(星期二) 下午5:07
收件人: "liuyishengalan/ThinkPad-P52-Hackintosh-10.14.X-"<ThinkPad-P52-Hackintosh-10.14.X-@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"redim"<fangjimjim@qq.com>;
主题: Re: [liuyishengalan/ThinkPad-P52-Hackintosh-10.14.X-] 这是测通了吗? (#1)



i7 8750h
quadro p1000
32G ddr4 2666 hyper x
4k display
disk: WD black SN700 & Samsung 970evo

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―
